import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import 'react-notifications-component/dist/theme.css'
// import 'animate.css/animate.min.css';
import AppBar from "./components/AppBar";
import SideBar from "./components/SideBar";
import { ContextProvider } from "./components/SideBarContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const revalidate = 3600;

const checklogin = async () => {
  try {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL}/api/example/`,
      {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include",
      }
    );
    if (response.ok) {
      // window.location.href = "/";
    }
  }
  catch (error) {
    console.log("Network error");
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <AppBar />
          <div className="h-full w-full flex">
            <SideBar />
            <div className="w-full h-full overflow-scroll">{children}</div>
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
