# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build And Deploy Web App

on:
  push:
    branches: [ "main" ]
    paths: ["apps/web/**"]
jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create .env file
      run: | 
        touch apps/web/.env
        echo "${{ secrets.WEB_ENV }}" > apps/web/.env
    - name: Install Dependencies
      run: yarn install
    - name: Build NextJS Application
      run: yarn workspace web run build
    - name: Restart PM2
      run: pm2 restart frontend-web
